### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by sscerr** [ottaviofornieri/Diffusion_MHD_modes#4]
The solver runs quite slow right now. To improve performances, parallelization is definitely required (e.g., at least in the variable associated to CRs' energy). We'll have to look into this.

**Comment by ottaviofornieri** [comment]
It's actually the part related to the Alfvén modes that makes it very slow, otherwise it takes a couple of minutes. But sure, parallelizing is certainly a good idea.

**Comment by sscerr** [comment]
Simplifying one loop in the calculation for Alfvénic modes seems to do the trick.
